var crossword = {
  w: 12, h: 12,
  grid: [
    'CONSUMERISME',
    'ORDINATEUR V',
    'RAGEA APL MI',
    'PU RUSTRERIE',
    'OXER OSES LR',
    'R RADIUS MOS',
    'AAR VENERER ',
    'TREND INONDA',
    'IGUE TETUE N',
    'SURIR NEGRES',
    'ME GUINEE CE',
    'ERIE DESSOUS'
  ],
  tips: [
    // horizontalement
    {x: 0, y: 0, w: 12, def: 'Philosophie d\'achat.'},
    {x: 0, y: 1, w: 10, def: 'Responsable des calculs.'},
    {x: 0, y: 2, w: 5, def: 'Il grinça des dents.'},
    {x: 6, y: 2, w: 3, def: 'Soutien pour un toit.'},
    {x: 10, y: 2, w: 2, def: 'La bonne note.'},
    {x: 0, y: 3, w: 2, def: 'Fut capable.'},
    {x: 3, y: 3, w: 9, def: 'Art des brutes.'},
    {x: 0, y: 4, w: 4, def: 'Obstacle de compétition.'},
    {x: 5, y: 4, w: 4, def: 'Tu peux le faire.'},
    {x: 10, y: 4, w: 2, def: 'Sens de lecture.'},
    {x: 2, y: 5, w: 6, def: 'Segment d\'écolier.'},
    {x: 9, y: 5, w: 3, def: 'Conducteur de circuits.'},
    {x: 0, y: 6, w: 3, def: 'Amène au Rhin.'},
    {x: 4, y: 6, w: 7, def: 'Rendre au sacré.'},
    {x: 0, y: 7, w: 5, def: 'Tendance économique.'},
    {x: 6, y: 7, w: 6, def: 'Se laissa déborder.'},
    {x: 0, y: 8, w: 4, def: 'Eau des Causses.'},
    {x: 5, y: 8, w: 5, def: 'Volontaire.'},
    {x: 0, y: 9, w: 5, def: 'Macérer.'},
    {x: 6, y: 9, w: 6, def: 'Entourent le colon.'},
    {x: 0, y: 10, w: 2, def: 'Personnel'},
    {x: 3, y: 10, w: 6, def: 'Or noir.'},
    {x: 10, y: 10, w: 2, def: 'Je le désigne.'},
    {x: 0, y: 11, w: 4, def: 'Port de Pennsylvanie.'},
    {x: 5, y: 11, w: 7, def: 'Pour les intimes.'},
    // verticalement
    {x: 0, y: 0, h: 12, def: 'Esprit de groupe.'},
    {x: 1, y: 0, h: 5, def: 'Notés de vive voix.'},
    {x: 1, y: 6, h: 6, def: 'Ne pas manquer d\'arguments.'},
    {x: 2, y: 0, h: 3, def: 'Danse communiste.'},
    {x: 2, y: 4, h: 6, def: 'Le propre de l\'homme.'},
    {x: 3, y: 0, h: 6, def: 'Avant le tango.'},
    {x: 3, y: 7, h: 5, def: 'On l\'appelle blanche.'},
    {x: 4, y: 0, h: 4, def: 'À deux doigts de la paresse.'},
    {x: 4, y: 5, h: 3, def: 'Fin de l\'analogique.'},
    {x: 4, y: 9, h: 2, def: 'Ruisseau.'},
    {x: 5, y: 0, h: 2, def: 'Je l\'ai.'},
    {x: 5, y: 3, h: 4, def: 'Venue d\'asie.'},
    {x: 5, y: 10, h: 2, def: 'Numéro de référence.'},
    {x: 6, y: 0, h: 12, def: 'Fille d\'oncle Sam.'},
    {x: 7, y: 0, h: 12, def: 'Absentes.'},
    {x: 8, y: 0, h: 5, def: 'Elles ont plus de pattes avec l\'âge.'},
    {x: 8, y: 6, h: 6, def: 'Couleurs soviétiques.'},
    {x: 9, y: 0, h: 2, def: 'Ancien junior.'},
    {x: 9, y: 5, h: 5, def: 'Guider.'},
    {x: 10, y: 2, h: 6, def: 'Chanté par le piaf.'},
    {x: 10, y: 9, h: 3, def: 'Protège des coups.'},
    {x: 11, y: 0, h: 6, def: 'Faiences.'},
    {x: 11, y: 7, h: 5, def: 'Chéries des porteurs d\'eau.'}
  ]
}
